openapi: 3.0.0
info:
  title: LiteraryHub AI API
  version: 1.0.0
  description: |
    The LiteraryHub AI API provides a robust suite of tools tailored for publishers and authors. It facilitates the creation of audiobooks from texts, generation of custom book covers, and updates to unpublished manuscripts in Word or PDF formats. Key features include plagiarism detection and identification of restricted topics, empowering users to create and refine content with confidence and compliance. This API serves as a comprehensive resource for automating and enhancing the publication process.
    
paths:
  /extractor/extract-text-pdf:
    get:
      tags:
        - text extractor
      summary: Extracts text from a PDF file
      description: |
        Extracts text from a PDF file using Optical Character Recognition (OCR) configured specifically for Arabic text. The endpoint requires a valid PDF file path and returns the extracted text as JSON.
      operationId: extractTextFromPDF
      parameters:
        - in: query
          name: file_path
          required: true
          schema:
            type: string
          description: The path to the PDF file
      responses:
        '200':
          description: Text extraction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: integer
                        text:
                          type: string
                        paragraph_index:
                          type: number
                    description: An array of objects containing page numbers and extracted texts.
        '400':
          description: Invalid file format or file does not exist
        '500':
          description: Error during text extraction
          
  /extractor/extract-text-word:
    get:
      tags:
        - text extractor
      summary: Extracts text from a Word document
      description: |
        Extracts text from a Word (.docx) document using a simple text extraction process. The endpoint needs a valid Word file path and returns the extracted text as JSON.
      operationId: extractTextFromWord
      parameters:
        - in: query
          name: file_path
          required: true
          schema:
            type: string
          description: The path to the Word file
      responses:
        '200':
          description: Text extraction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: string
                          example: Not directly available
                        text:
                          type: string
                        paragraph_index:
                          type: number
                    description: An array of objects containing page numbers and extracted texts.
        '400':
          description: Invalid file format or file does not exist
        '500':
          description: Error during text extraction

  /audiobook/v2/text-to-speech:
    post:
      tags:
        - audiobook
      summary: Converts text to speech
      description: This endpoint receives text and converts it into spoken audio, streaming it back as a WAV file. Ideal for transforming book content into an easily accessible audiobook format.
      operationId: textToSpeechV2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookTextBody'
      responses:
        '200':
          description: Successfully streams the generated audio
          content:
            audio/wav:
              schema:
                type: string
                format: binary
                description: The audio stream of the spoken text in WAV format.
        '400':
          description: Invalid request data
        '500':
          description: Server error
  
  /book-cover/generate:
    post:
      tags:
        - book cover generator
      summary: Generates a custom book cover
      description: |
        Generates a custom book cover based on the provided title, summary, and authors. This endpoint is designed to create visually appealing covers for Arabic books, utilizing details such as the book title, summary, and author names to influence the design. The response includes the generated cover image in PNG format.
      operationId: generateBookCover
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                book_title:
                  type: string
                  description: Title of the book for which the cover is being generated.
                book_summary:
                  type: string
                  description: A brief summary of the book that can influence the cover's design.
                arabic_authors:
                  type: array
                  items:
                    type: string
                  description: List of Arabic authors' names to be featured on the book cover.
                num_inference_steps:
                  type: integer
                  default: 5
                  description: Number of inference steps to be used in the generation process.
                guidance_scale:
                  type: number
                  default: 0.6
                  description: The scale of guidance applied during the cover generation to maintain relevance to the input parameters.
      responses:
        '200':
          description: Successfully generated the book cover.
          content:
            image/png:
              schema:
                type: string
                format: binary
                description: The generated book cover image in PNG format.
        '400':
          description: Invalid input parameters
        '500':
          description: Server error
  
  /restricted-topic-detection/v1/detect:
    post:
      summary: Detect Restricted Content
      tags:
        - restricted topic detection
      description: Endpoint for detecting restricted content in a list of extracted texts.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                extracted_texts:
                  type: array
                  items:
                    type: object
                    required:
                      - page_number
                      - paragraph_index
                      - text
                    properties:
                      page_number:
                        type: integer
                        description: The page number where the text is found.
                        example: 1
                      paragraph_index:
                        type: integer
                        description: The paragraph index on the page.
                        example: 1
                      text:
                        type: string
                        description: The extracted text content.
                        example: "This is a sample text."
            example:
              extracted_texts:
                - page_number: 1
                  paragraph_index: 1
                  text: "This is a sample text."
                - page_number: 1
                  paragraph_index: 2
                  text: "This is another sample text."

      responses:
        200:
          description: The JSON input with the restricted content detection results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: integer
                        paragraph_index:
                          type: integer
                        text:
                          type: string
                        is_safe:
                          type: boolean
                          description: Flag indicating if the text is safe or restricted.
                          example: true
                example:
                  extracted_texts:
                    - page_number: 1
                      paragraph_index: 1
                      text: "This is a sample text."
                      is_safe: true
                    - page_number: 1
                      paragraph_index: 2
                      text: "This is another sample text."
                      is_safe: true
        400:
          description: No extracted texts provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "No extracted texts provided"
                    
  /restricted-topic-detection/v2/detect:
    post:
      summary: Detect Restricted Content
      tags:
        - restricted topic detection
      description: Endpoint for detecting restricted content in a list of extracted texts.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                extracted_texts:
                  type: array
                  items:
                    type: object
                    required:
                      - page_number
                      - paragraph_index
                      - text
                    properties:
                      page_number:
                        type: integer
                        description: The page number where the text is found.
                        example: 1
                      paragraph_index:
                        type: integer
                        description: The paragraph index on the page.
                        example: 1
                      text:
                        type: string
                        description: The extracted text content.
                        example: "This is a sample text."
            example:
              extracted_texts:
                - page_number: 1
                  paragraph_index: 1
                  text: "This is a sample text."
                - page_number: 1
                  paragraph_index: 2
                  text: "This is another sample text."

      responses:
        200:
          description: The JSON input with the restricted content detection results.
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: integer
                        paragraph_index:
                          type: integer
                        text:
                          type: string
                        is_safe:
                          type: boolean
                          description: Flag indicating if the text is safe or restricted.
                          example: true
                example:
                  extracted_texts:
                    - page_number: 1
                      paragraph_index: 1
                      text: "This is a sample text."
                      is_safe: true
                    - page_number: 1
                      paragraph_index: 2
                      text: "This is another sample text."
                      is_safe: true
        400:
          description: No extracted texts provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "No extracted texts provided"
      
  
  /pipeline/author-pipeline:
    post:
      summary: Processes a book file and inserts it into the database.
      description: >
        This endpoint handles the ingestion and processing of book documents. It supports files in PDF and Word formats. Upon receiving the request, it checks the file existence and format, extracts the text, and performs necessary preprocessing before inserting the book details into the database. This process includes registering the book title, authors, and summary, and associates it with the extracted content. It is designed to streamline the management of book records within a digital library system.
      operationId: authorPipeline
      tags:
        - book processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
            example:
              file_path: "/path/to/book.pdf"
              title: "My Book"
              authors_ids: [1, 2]
              book_summary: "This is a book about..."
      responses:
        '200':
          description: Successfully processed and inserted the book data. Returns the book ID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  book_id:
                    type: integer
                    description: The ID of the book that was inserted into the database.
        '400':
          description: The file format is not supported. Only PDF and Word files are supported.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        '404':
          description: The file specified in the payload does not exist.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
        '500':
          description: An error occurred while processing the file.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
          
components:
  schemas:
    BookTextBody:
      type: object
      required:
        - text
        - book_name
      properties:
        text:
          type: string
          description: The text to be converted into speech
        book_name:
          type: string
          description: The name of the book associated with the text
    Book:
      type: object
      properties:
        file_path:
          type: string
          description: Path to the book file.
        title:
          type: string
          description: Title of the book.
        authors_ids:
          type: array
          items:
            type: integer
          description: IDs of the authors of the book.
        book_summary:
          type: string
          description: Summary of the book.